### ISSUE TITLE
pelase  update Invoke  to v3.1.0

### ISSUE THREAD

**Issue by wolfkingal2000** [MikeEmmett/InvokeAI#3]
pelase  update Invoke  to v3.1.0

**Comment by ImMikeEmmett** [comment]
Hello!
The "Default Version" in the advanced options is currently running 3.1.0. I understand this was posted last week when it may not have been. However you can force any version by typing the version number into the "Version" box in the "Advanced options" section.
However.. I have specifically added 3.1.0 to the dropdown anyway.
